# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - escola-de-cursos-backend

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  migrate:
    runs-on: windows-latest
    needs: build
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set Up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.x"

      - name: Restore dependencies
        run: dotnet restore WebApp/EscolaDeCursos.WebApp.csproj

      - name: Install Entity Framework client
        run: dotnet tool install --global dotnet-ef

      - name: Apply ORM Migrations
        env:
          SQLSERVER_CONNECTIONSTRING: ${{ secrets.SQLSERVER_CONNECTIONSTRING }}
        run: |
          dotnet ef database update `
            --project "WebApp/EscolaDeCursos.WebApp.csproj" `
            --configuration Release `
            --connection "$env:SQLSERVER_CONNECTIONSTRING"

  deploy:
    runs-on: windows-latest
    needs: [build, migrate]
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BF273FAF92284C6CA3D5EE2990522865 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AA19F09D7D4941088F3DA3E315333402 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DC134AE11A4240DFB3CE88041D0880B6 }}

      - name: Configure Azure Web App settings
        shell: pwsh
        run: |
          az webapp config appsettings set `
            --resource-group "escola-de-cursos-backend" `
            --name "escola-de-cursos-backend" `
            --settings `
             "ConnectionStrings__SqlServer=${{ secrets.SQLSERVER_CONNECTIONSTRING }}"

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'escola-de-cursos-backend'
          slot-name: 'Production'
          package: .
